// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfxhvrpcgxlmyxisecef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmeGh2cnBjZ3hsbXl4aXNlY2VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzOTI0NjYsImV4cCI6MjA3NTk2ODQ2Nn0.2gBSR9_D2oprkNcosrhxfXTJ6_uDKB1VUc7Vkrew70I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});